CREATE VIEW midwifeinfo
AS
    SELECT PRACTID, M.NAME AS MIDWIFE_NAME, PHONENUM, MEMAIL AS M_EMAIL, I.NAME AS INST_NAME, ADDRESS
FROM MIDWIFE M LEFT JOIN INSTITUTIONS I on M.EMAIL = I.EMAIL
WHERE I.EMAIL IN (SELECT EMAIL FROM FACILITY)
;

DROP VIEW midwifeinfo;

SELECT * FROM midwifeinfo
LIMIT(5);

SELECT * FROM midwifeinfo
WHERE INST_NAME = 'Lac-Saint-Louis'
LIMIT(5);

INSERT INTO midwifeinfo (PRACTID, MIDWIFE_NAME, PHONENUM, M_EMAIL, INST_NAME, ADDRESS)
VALUES
(2007, 'Alice Kim', 10101010, 'a.kim@gmail.com', 'General Hospital', '3006 Hillcrest Lane')
;