CREATE VIEW midwifeinfo
AS
    SELECT PRACTID, M.NAME AS MIDWIFE_NAME, PHONENUM, MEMAIL AS M_EMAIL, I.NAME AS INST_NAME, ADDRESS
FROM MIDWIFE M LEFT JOIN INSTITUTIONS I on M.EMAIL = I.EMAIL
WHERE I.EMAIL IN (SELECT EMAIL FROM FACILITY)
;

DROP VIEW midwifeinfo;

SELECT * FROM midwifeinfo;